server:
  port: 8082
spring:
  application:
    name: Service
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/health?serverTimezone=GMT%2B8
      username: root
      password: root
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848
  devtools:
    restart:
      # 设置开启热部署
      enabled: true
      # 启用热部署的目录
      additional-paths: src/main/java
  jackson:
    date-format: yyyy-MM-dd
    time-zone: 'GMT+8'
  mvc:
    format:
      date: yyyy-MM-dd
mybatis-plus:
  global-config:
    db-config:
      table-prefix: h_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: error
#    com.xzh.service: debug
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
feign:
  client:
    config:
      default:
        loggerlevel: FULL
  # feign性能优化，开启httpclient连接池
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50


