server:
  port: 10086
spring:
  application:
    name: SubtleChat
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/subtleChat?serverTimezone=UTC
      username: root
      password: root
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848
        namespace: 056fac36-f20b-4863-9820-71d3deac550a
  mail:
    host: smtp.qq.com
    port: 587
    username: 2514769607@qq.com
    password: uarbukoggvgpdhgi
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
fastdfs:
  nginx:
    host: http://39.108.169.57/
